"""Changed taxonomy FK to manytomany

Revision ID: 092b93bc3a73
Revises: 70713f13acdc
Create Date: 2016-02-17 12:53:16.908873

"""

# revision identifiers, used by Alembic.
revision = '092b93bc3a73'
down_revision = '70713f13acdc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie_taxonomy',
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specie_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], )
    )
    op.drop_constraint(u'taxonomies_specie_id_fkey', 'taxonomies', type_='foreignkey')
    op.drop_column(u'taxonomies', 'specie_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'taxonomies', sa.Column('specie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'taxonomies_specie_id_fkey', 'taxonomies', 'species', ['specie_id'], ['id'])
    op.drop_table('specie_taxonomy')
    ### end Alembic commands ###
