"""Changed species fk field

Revision ID: 22b42208e7bc
Revises: 9c07e97d6cd4
Create Date: 2016-02-13 09:54:53.418926

"""

# revision identifiers, used by Alembic.
revision = '22b42208e7bc'
down_revision = '9c07e97d6cd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomes', sa.Column('specie_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'genomes_specie_fkey', 'genomes', type_='foreignkey')
    op.create_foreign_key(None, 'genomes', 'species', ['specie_id'], ['id'])
    op.drop_column('genomes', 'specie')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomes', sa.Column('specie', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genomes', type_='foreignkey')
    op.create_foreign_key(u'genomes_specie_fkey', 'genomes', 'species', ['specie'], ['id'])
    op.drop_column('genomes', 'specie_id')
    ### end Alembic commands ###
