"""empty message

Revision ID: 277243e11cdd
Revises: b1bf638c0df9
Create Date: 2016-07-10 14:04:27.992944

"""

# revision identifiers, used by Alembic.
revision = '277243e11cdd'
down_revision = 'b1bf638c0df9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('clustering_inflation_value', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'clustering_inflation_value')
    ### end Alembic commands ###
