"""Add index to Protein name

Revision ID: 5afba87379a3
Revises: 77f3cd39f8e7
Create Date: 2016-02-17 19:53:15.608769

"""

# revision identifiers, used by Alembic.
revision = '5afba87379a3'
down_revision = '77f3cd39f8e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_proteins_name'), 'proteins', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proteins_name'), table_name='proteins')
    ### end Alembic commands ###
