"""Added indexes to speedup cluster queries

Revision ID: 88698767003e
Revises: 5afba87379a3
Create Date: 2016-02-20 13:26:54.945431

"""

# revision identifiers, used by Alembic.
revision = '88698767003e'
down_revision = '5afba87379a3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cluster_protein_cluster_id'), 'cluster_protein', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_protein_protein_id'), 'cluster_protein', ['protein_id'], unique=False)
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_index(op.f('ix_proteins_genome_id'), 'proteins', ['genome_id'], unique=False)
    op.create_index(op.f('ix_proteins_id'), 'proteins', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proteins_id'), table_name='proteins')
    op.drop_index(op.f('ix_proteins_genome_id'), table_name='proteins')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_index(op.f('ix_cluster_protein_protein_id'), table_name='cluster_protein')
    op.drop_index(op.f('ix_cluster_protein_cluster_id'), table_name='cluster_protein')
    ### end Alembic commands ###
