"""Changed Genome column names

Revision ID: 9c07e97d6cd4
Revises: fc17182be568
Create Date: 2016-02-13 09:34:06.718445

"""

# revision identifiers, used by Alembic.
revision = '9c07e97d6cd4'
down_revision = 'fc17182be568'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomes', sa.Column('genome_name', sa.String(), nullable=True))
    op.add_column('genomes', sa.Column('specie', sa.Integer(), nullable=True))
    op.drop_constraint(u'genomes_taxon_id_fkey', 'genomes', type_='foreignkey')
    op.create_foreign_key(None, 'genomes', 'species', ['specie'], ['id'])
    op.drop_column('genomes', 'taxon_id')
    op.drop_column('genomes', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('genomes', sa.Column('taxon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genomes', type_='foreignkey')
    op.create_foreign_key(u'genomes_taxon_id_fkey', 'genomes', 'species', ['taxon_id'], ['id'])
    op.drop_column('genomes', 'specie')
    op.drop_column('genomes', 'genome_name')
    ### end Alembic commands ###
