"""Added link between genome and protein

Revision ID: fb026f3d6a41
Revises: 22b42208e7bc
Create Date: 2016-02-13 11:14:32.358411

"""

# revision identifiers, used by Alembic.
revision = 'fb026f3d6a41'
down_revision = '22b42208e7bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genes')
    op.add_column('proteins', sa.Column('gene_name', sa.String(), nullable=True))
    op.add_column('proteins', sa.Column('genome_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proteins', 'genomes', ['genome_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proteins', type_='foreignkey')
    op.drop_column('proteins', 'genome_id')
    op.drop_column('proteins', 'gene_name')
    op.create_table('genes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'genes_pkey')
    )
    ### end Alembic commands ###
