"""Initial revision

Revision ID: fc17182be568
Revises: 
Create Date: 2016-02-10 21:18:34.732390

"""

# revision identifiers, used by Alembic.
revision = 'fc17182be568'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proteins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('aminoacid_sequence', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('taxon_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_protein',
    sa.Column('protein_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], )
    )
    op.create_table('functional_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('go_term', sa.String(), nullable=True),
    sa.Column('signalp', sa.String(), nullable=True),
    sa.Column('tmhmm', sa.String(), nullable=True),
    sa.Column('pfam', sa.String(), nullable=True),
    sa.Column('KEGG', sa.String(), nullable=True),
    sa.Column('KOG', sa.String(), nullable=True),
    sa.Column('protein_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('taxon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genomes')
    op.drop_table('functional_annotations')
    op.drop_table('cluster_protein')
    op.drop_table('species')
    op.drop_table('proteins')
    op.drop_table('genes')
    op.drop_table('clusters')
    ### end Alembic commands ###
